services:
  cumplo-accountant:
    image: cumplo-accountant
    env_file: .env
    ports:
      - 8004:8080
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - CUMPLO_PYPI_BASE64_KEY
    volumes:
      - ./cumplo_accountant:/app/cumplo_accountant
